version: '3.9'
services:
  app:
    build: .
    container_name: sus-dx_auth_server
    ports:
      - 8888:80
    volumes:
      - /home/cam/secret:/work/keys
      - /home/cam/logs:/work/logs
    networks:
      sus-dx-auth-network:
        ipv4_address: 192.1.1.3
networks:
  sus-dx-auth-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.1.1.0/24